name: course_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  # simple_animations: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # flutter_spinkit: ^5.2.0
  firebase_auth: ^4.16.0
  hexcolor: ^3.0.1
  # pinput: ^4.0.0
  # timer_count_down: ^2.2.2
  # flutter_timer_countdown: ^1.0.7
  # intl_phone_field: ^3.2.0
  provider: ^6.1.1
  font_awesome_flutter: ^10.6.0
  awesome_bottom_bar: ^1.2.4
  skeletonizer: ^1.0.1
  carousel_slider: ^4.2.1
  infinite_carousel: ^1.0.3
  mailer: ^6.0.1
  flutter_carousel_widget: ^2.2.0
  firebase_ui_auth: ^1.13.0
  firebase_ui_oauth_google: ^1.3.0
  cached_network_image: ^3.3.1
  banner_listtile: ^2.3.0
  flexivideoplayer: ^0.1.1
  video_player: ^2.8.2
  path_provider: ^2.1.2
  flutter_cached_pdfview: ^0.4.2
  flutter_windowmanager: ^0.2.0
  razorpay_flutter: ^1.3.0
  radio_group_v2: ^3.1.0
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  empty_widget:
    git:
      url: https://github.com/godstark82/empty_widget_fork.git
      ref: migrated-branch
  flutter_onboarding_slider: ^1.0.11
  gradient_borders: ^1.0.0
  onesignal_flutter: ^5.1.2
  line_icons: ^2.0.3
  url_launcher: ^6.2.5
  ionicons: ^0.2.2
  whatsapp_share2: ^2.0.2
  http: ^1.2.1
  path: ^1.9.0
  device_preview: ^1.1.0
  flutter_svg: ^2.0.10+1
  velocity_x: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/anim/
    - assets/images/
    - assets/images/slide_1.png
    - assets/images/slide_2.png
    - assets/images/slide_3.png
    - assets/images/notepediax_white.png
    - assets/images/notepediax_black.png
    - shorebird.yaml

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Naruto
      fonts:
        - asset: assets/fonts/naruto.ttf
        - asset: assets/fonts/naruto_variable.ttf
          weight: 900
